language: go
go:
  - 1.10.x

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  - go test -v ./...

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --replace --prerelease --debug pre-release dist/
